name: Build
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Commit Hash
        run: |
          echo 'export GIT_HASH=$(git rev-parse HEAD)' >> $BASH_ENV
      - name: Build image
        run: |
          HASH=$GIT_HASH make
